---
title: "Plotly"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

Making interactive plots!

```{r load libraries, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)

library(plotly)
```

Focus on Instacart data

```{r import and filter data}
data("instacart")

instacart = 
  instacart |> 
  as_tibble() 

```


### Scatterplot

```{r scatterplot}
instacart |> 
  count(aisle) |> 
  filter(n > 10000) |> 
  mutate(text_label = str_c("Count", n, "\nAisle: ", aisle)) |> 
  plot_ly(x = ~aisle, y = ~n, color = ~n, 
          type = "scatter", mode = "markers")
```

### Line Plot

```{r lineplot}
instacart |> 
  count(aisle) |> 
  filter(n > 10000) |> 
  mutate(text_label = str_c("Count", n, "\nAisle: ", aisle)) |> 
  plot_ly(x = ~aisle, y = ~n, 
          type = "scatter", mode = "lines") 

```

### Bar Chart

```{r bar chart}
instacart |> 
  count(aisle) |> 
  mutate(aisle = fct_reorder(aisle, n)) |> 
  plot_ly(x = ~aisle, y = ~n, color = ~aisle, type = "bar", colors = "viridis")
```





